"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, CalendarClock, CheckCircle2, Download, FileUp, PiggyBank, RefreshCw, Scale, Upload } from "lucide-react";
import Navbar from "@/components/Navbar";
import { Button } from "@/components/ui/Button";
import { EmptyState } from "@/components/ui/EmptyState";
import { Field, fieldControlStyles } from "@/components/ui/Field";
import { PageHeader } from "@/components/ui/PageHeader";
import { Surface } from "@/components/ui/Surface";
import { buildBudgetProgress, buildFinancialAlerts, buildReconciliation, parseTransactionCsv, serializeTransactionsCsv } from "@/lib/financial-control";
import { supabase } from "@/infrastructure/supabase/browser-client";

type Account = { id: string; name: string; current_balance: number; updated_at: string };
type Transaction = { id: string; date: string; type: "income" | "expense"; merchant: string | null; category: string; amount: number; note: string | null; status: "confirmed" | "pending_approval" | "needs_review" | "deleted" };
type Budget = { id: string; category: string; month: string; limit_amount: number };
type Recurring = { id: string; merchant: string; category: string; amount: number; type: "income" | "expense"; interval: string; next_run_date: string; is_active: boolean; account_id: string };
const today = new Date().toISOString().slice(0, 10);
const month = `${today.slice(0, 7)}-01`;
const idr = new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 });

export default function PlanningPage() {
  const [accounts, setAccounts] = useState<Account[]>([]); const [transactions, setTransactions] = useState<Transaction[]>([]); const [budgets, setBudgets] = useState<Budget[]>([]); const [recurring, setRecurring] = useState<Recurring[]>([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const [budgetForm, setBudgetForm] = useState({ category: "", month, limitAmount: "" });
  const [recurringForm, setRecurringForm] = useState({ accountId: "", merchant: "", category: "", amount: "", type: "expense" as const, interval: "monthly", nextRunDate: today });
  const [reconcileForm, setReconcileForm] = useState({ accountId: "", statementBalance: "" }); const [importAccountId, setImportAccountId] = useState(""); const importRef = useRef<HTMLInputElement>(null);

  const load = useCallback(async () => {
    setLoading(true); setMessage(null);
    const { data: { user } } = await supabase.auth.getUser(); if (!user) { setLoading(false); return; }
    const [accountsResult, txResult, budgetsResult, recurringResult] = await Promise.all([
      supabase.from("financial_accounts").select("id,name,current_balance,updated_at").eq("user_id", user.id).eq("is_active", true).order("name"),
      supabase.from("transactions").select("id,date,type,merchant,category,amount,note,status").eq("user_id", user.id).gte("date", `${today.slice(0, 7)}-01`).order("date", { ascending: false }),
      supabase.from("financial_budgets").select("id,category,month,limit_amount").eq("user_id", user.id).eq("month", month),
      supabase.from("recurring_transactions").select("id,merchant,category,amount,type,interval,next_run_date,is_active,account_id").eq("user_id", user.id).eq("is_active", true).order("next_run_date"),
    ]);
    const error = accountsResult.error || txResult.error || budgetsResult.error || recurringResult.error;
    if (error) setMessage("Data planning belum berhasil dimuat. Pastikan migrasi terbaru sudah dijalankan.");
    else { setAccounts((accountsResult.data ?? []) as Account[]); setTransactions((txResult.data ?? []) as Transaction[]); setBudgets((budgetsResult.data ?? []) as Budget[]); setRecurring((recurringResult.data ?? []) as Recurring[]); }
    setLoading(false);
  }, []);
  useEffect(() => { void load(); }, [load]);
  const alerts = useMemo(() => buildFinancialAlerts({ budgets: budgets.map((b) => ({ category: b.category, limitAmount: Number(b.limit_amount), month: b.month.slice(0, 7) })), transactions, accountFreshness: accounts.map((a) => ({ accountName: a.name, lastUpdatedAt: a.updated_at })), today }), [accounts, budgets, transactions]);
  const categories = useMemo(() => [...new Set(transactions.filter((tx) => tx.type === "expense").map((tx) => tx.category))], [transactions]);

  async function saveBudget(event: React.FormEvent) { event.preventDefault(); setSaving(true); setMessage(null); const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { error } = await supabase.from("financial_budgets").upsert({ user_id: user.id, category: budgetForm.category, month: `${budgetForm.month.slice(0, 7)}-01`, limit_amount: Number(budgetForm.limitAmount) }, { onConflict: "user_id,category,month" }); setSaving(false); if (error) setMessage("Budget belum tersimpan."); else { setBudgetForm({ category: "", month, limitAmount: "" }); await load(); } }
  async function saveRecurring(event: React.FormEvent) { event.preventDefault(); setSaving(true); const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { error } = await supabase.from("recurring_transactions").insert({ user_id: user.id, account_id: recurringForm.accountId, merchant: recurringForm.merchant, category: recurringForm.category, amount: Number(recurringForm.amount), type: recurringForm.type, interval: recurringForm.interval, next_run_date: recurringForm.nextRunDate }); setSaving(false); if (error) setMessage("Jadwal transaksi belum tersimpan."); else { setRecurringForm({ accountId: "", merchant: "", category: "", amount: "", type: "expense", interval: "monthly", nextRunDate: today }); await load(); } }
  async function reconcile(event: React.FormEvent) { event.preventDefault(); const account = accounts.find((item) => item.id === reconcileForm.accountId); if (!account) return; setSaving(true); const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { error } = await supabase.from("account_reconciliations").insert({ user_id: user.id, account_id: account.id, statement_balance: Number(reconcileForm.statementBalance), ledger_balance: Number(account.current_balance), reconciled_at: today }); setSaving(false); setMessage(error ? "Rekonsiliasi belum tersimpan." : "Rekonsiliasi tersimpan. Selisihnya tercatat untuk ditindaklanjuti."); if (!error) setReconcileForm({ accountId: "", statementBalance: "" }); }
  async function runRecurring(ruleId: string) { setSaving(true); const { error } = await supabase.rpc("run_recurring_transaction", { rule_id: ruleId }); setSaving(false); setMessage(error ? "Jadwal belum dapat dijalankan. Pastikan tanggalnya sudah jatuh tempo." : "Transaksi berulang sudah masuk ke ledger dan jadwal berikutnya diperbarui."); if (!error) await load(); }
  function downloadCsv() { const blob = new Blob([serializeTransactionsCsv(transactions)], { type: "text/csv;charset=utf-8" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `fintrack-${today}.csv`; link.click(); URL.revokeObjectURL(link.href); }
  async function importCsv(file: File) { if (!importAccountId) { setMessage("Pilih akun tujuan sebelum impor CSV."); return; } try { const records = parseTransactionCsv(await file.text()); const { data: { user } } = await supabase.auth.getUser(); if (!user) return; setSaving(true); const { error } = await supabase.from("transactions").insert(records.map((row) => ({ ...row, user_id: user.id, account_id: importAccountId, source: "manual", status: "needs_review" }))); setSaving(false); if (error) throw error; setMessage(`${records.length} transaksi diimpor sebagai Perlu ditinjau.`); await load(); } catch { setSaving(false); setMessage("CSV tidak dapat diimpor. Gunakan format ekspor FinTrack."); } }

  return <div className="app-page"><Navbar /><main className="app-page-content max-w-6xl space-y-6"><PageHeader eyebrow="Financial control" title="Rencana & kontrol" description="Atur budget, jadwal transaksi, cocokkan saldo, dan pindahkan data dengan aman." actions={<Button variant="secondary" onClick={downloadCsv}><Download className="h-4 w-4" /> Ekspor CSV</Button>} />
    {message && <div role="alert" className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">{message}</div>}
    {alerts.length > 0 && <Surface className="p-5"><h2 className="flex items-center gap-2 font-bold"><AlertTriangle className="h-5 w-5 text-amber-600" /> Perlu perhatian</h2><ul className="mt-3 space-y-2 text-sm text-slate-600">{alerts.map((alert, index) => <li key={`${alert.kind}-${index}`} className="rounded-lg bg-slate-50 px-3 py-2">{alert.message}</li>)}</ul></Surface>}
    <div className="grid gap-6 lg:grid-cols-2"><Surface className="p-5"><h2 className="flex items-center gap-2 text-lg font-bold"><PiggyBank className="h-5 w-5 text-emerald-700" /> Budget kategori</h2><form onSubmit={saveBudget} className="mt-4 grid gap-3 sm:grid-cols-3"><select required value={budgetForm.category} onChange={(e) => setBudgetForm({ ...budgetForm, category: e.target.value })} className={fieldControlStyles}><option value="">Kategori</option>{categories.map((category) => <option key={category}>{category}</option>)}</select><input required type="month" value={budgetForm.month.slice(0, 7)} onChange={(e) => setBudgetForm({ ...budgetForm, month: `${e.target.value}-01` })} className={fieldControlStyles} /><input required min="1" inputMode="numeric" type="number" placeholder="Batas IDR" value={budgetForm.limitAmount} onChange={(e) => setBudgetForm({ ...budgetForm, limitAmount: e.target.value })} className={fieldControlStyles} /><Button disabled={saving} className="sm:col-span-3">Simpan budget</Button></form><div className="mt-5 space-y-3">{budgets.map((budget) => { const progress = buildBudgetProgress({ category: budget.category, limitAmount: Number(budget.limit_amount), month: budget.month.slice(0, 7) }, transactions); return <div key={budget.id}><div className="flex justify-between text-sm"><span className="font-bold">{budget.category}</span><span>{idr.format(progress.spentAmount)} / {idr.format(progress.limitAmount)}</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-slate-100"><div className={progress.state === "over" ? "h-full bg-rose-500" : progress.state === "warning" ? "h-full bg-amber-500" : "h-full bg-emerald-500"} style={{ width: `${Math.min(progress.percentage, 100)}%` }} /></div></div>; })}</div></Surface>
      <Surface className="p-5"><h2 className="flex items-center gap-2 text-lg font-bold"><CalendarClock className="h-5 w-5 text-emerald-700" /> Transaksi berulang</h2><form onSubmit={saveRecurring} className="mt-4 grid gap-3 sm:grid-cols-2"><select required value={recurringForm.accountId} onChange={(e) => setRecurringForm({ ...recurringForm, accountId: e.target.value })} className={fieldControlStyles}><option value="">Akun</option>{accounts.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select><input required placeholder="Merchant / nama" value={recurringForm.merchant} onChange={(e) => setRecurringForm({ ...recurringForm, merchant: e.target.value })} className={fieldControlStyles} /><input required placeholder="Kategori" value={recurringForm.category} onChange={(e) => setRecurringForm({ ...recurringForm, category: e.target.value })} className={fieldControlStyles} /><input required type="number" min="1" placeholder="Nominal" value={recurringForm.amount} onChange={(e) => setRecurringForm({ ...recurringForm, amount: e.target.value })} className={fieldControlStyles} /><select value={recurringForm.interval} onChange={(e) => setRecurringForm({ ...recurringForm, interval: e.target.value })} className={fieldControlStyles}><option value="weekly">Mingguan</option><option value="monthly">Bulanan</option><option value="yearly">Tahunan</option></select><input required type="date" value={recurringForm.nextRunDate} onChange={(e) => setRecurringForm({ ...recurringForm, nextRunDate: e.target.value })} className={fieldControlStyles} /><Button disabled={saving} className="sm:col-span-2">Tambah jadwal</Button></form><div className="mt-5 space-y-2">{recurring.map((rule) => <div key={rule.id} className="flex items-center justify-between gap-3 rounded-lg bg-slate-50 px-3 py-2 text-sm"><span className="font-bold">{rule.merchant} · {rule.category}</span><span className="text-right">{rule.next_run_date} · {idr.format(Number(rule.amount))}<Button size="compact" variant="ghost" disabled={saving || rule.next_run_date > today} onClick={() => void runRecurring(rule.id)}>Jalankan</Button></span></div>)}</div></Surface></div>
    <div className="grid gap-6 lg:grid-cols-2"><Surface className="p-5"><h2 className="flex items-center gap-2 text-lg font-bold"><Scale className="h-5 w-5 text-emerald-700" /> Rekonsiliasi saldo</h2><form onSubmit={reconcile} className="mt-4 space-y-3"><select required value={reconcileForm.accountId} onChange={(e) => setReconcileForm({ ...reconcileForm, accountId: e.target.value })} className={fieldControlStyles}><option value="">Pilih akun</option>{accounts.map((a) => <option key={a.id} value={a.id}>{a.name} · catatan {idr.format(Number(a.current_balance))}</option>)}</select><Field label="Saldo menurut mutasi / statement" htmlFor="statement-balance"><input id="statement-balance" required type="number" value={reconcileForm.statementBalance} onChange={(e) => setReconcileForm({ ...reconcileForm, statementBalance: e.target.value })} className={fieldControlStyles} /></Field>{reconcileForm.accountId && reconcileForm.statementBalance && <p className="text-sm text-slate-600">{buildReconciliation({ expectedBalance: Number(accounts.find((a) => a.id === reconcileForm.accountId)?.current_balance), statementBalance: Number(reconcileForm.statementBalance) }).isMatched ? "Saldo cocok." : "Ada selisih yang perlu dicek."}</p>}<Button disabled={saving}><CheckCircle2 className="h-4 w-4" /> Simpan rekonsiliasi</Button></form></Surface>
      <Surface className="p-5"><h2 className="flex items-center gap-2 text-lg font-bold"><FileUp className="h-5 w-5 text-emerald-700" /> Impor CSV</h2><p className="mt-1 text-sm text-slate-500">Pilih CSV hasil ekspor FinTrack. Semua data masuk sebagai “Perlu ditinjau” agar aman.</p><select value={importAccountId} onChange={(e) => setImportAccountId(e.target.value)} className={`mt-4 w-full ${fieldControlStyles}`}><option value="">Akun tujuan</option>{accounts.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select><input ref={importRef} className="hidden" type="file" accept=".csv,text/csv" onChange={(e) => { const file = e.target.files?.[0]; if (file) void importCsv(file); e.currentTarget.value = ""; }} /><Button variant="secondary" className="mt-3" disabled={saving} onClick={() => importRef.current?.click()}><Upload className="h-4 w-4" /> Pilih file CSV</Button></Surface></div>
    {!loading && accounts.length === 0 && <Surface><EmptyState icon={RefreshCw} title="Buat akun dulu" description="Budget dan transaksi berulang membutuhkan akun tujuan untuk menjaga saldo tetap akurat." /></Surface>}
  </main></div>;
}
